project_root: '%DOC_GEN_LIB_PATH%'
templates_dir: '%DOC_GEN_LIB_PATH%/SelfDoc/Configuration/templates'
cache_dir: '%project_root%/SelfDoc/__cache'
language_handlers:
  php:
    class: \BumbleDocGen\LanguageHandler\Php\PhpHandler
    settings:
      file_source_base_url: 'https://***REMOVED***/blob/master'
      async_source_loading_enabled: true
source_locators:
  - class: \BumbleDocGen\Core\Parser\SourceLocator\RecursiveDirectoriesSourceLocator
    arguments:
      directories:
        - "%project_root%/BumbleDocGen"
        - "%project_root%/SelfDoc"
plugins:
  - class: \SelfDoc\Configuration\Plugin\RoaveStubber\BetterReflectionStubberPlugin
  - class: \SelfDoc\Configuration\Plugin\TwigFilterClassParser\TwigFilterClassParserPlugin
  - class: \SelfDoc\Configuration\Plugin\TwigFunctionClassParser\TwigFunctionClassParserPlugin