markdown: GFM
name: ""
title: null
remote_theme: tuur29/pages-themes-cayman
darkmode: true
buttons:
  zip_hide: true
  tar_hide: true
  github_hide: true
plugins:
  - jekyll-remote-theme
github:
  is_project_page: false
title-heading: false